[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.6.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go-v2"
  version = "2.0.0-preview.5"

[prune]
  go-tests = true
  unused-packages = true
